CREATE TABLE trips (
  id SERIAL NOT NULL PRIMARY KEY,
  uuid TEXT NOT NULL UNIQUE,
  date TIMESTAMP WITHOUT TIME ZONE,
  boat TEXT,
  crew JSONB,
  stations JSONB,
  uploaded_at TIMESTAMP WITHOUT TIME ZONE
);